version: '3'

services:
  dbScaffoldc:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_DEV}
    container_name: scaffoldc
    volumes:
      - ./postgres:/var/lib/postgresql/data
